spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movies_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect